# Generated by Django 2.1.5 on 2019-01-24 12:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
