# Generated by Django 2.1.5 on 2019-01-18 09:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_contant',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
