# Generated by Django 2.1.1 on 2019-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0002_auto_20190116_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_contant',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
