# Generated by Django 2.1.5 on 2019-01-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
