# Generated by Django 2.1.5 on 2019-01-25 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0003_auto_20190124_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_contant',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_contant',
            name='blog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chris.BlogType'),
        ),
    ]
