# Generated by Django 2.1.1 on 2019-01-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0003_auto_20190116_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_contant',
            name='content',
        ),
    ]
