# Generated by Django 2.1.1 on 2019-01-16 14:40

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0004_remove_blog_contant_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_contant',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
