apiVersion: v1
kind: PersistentVolume
metadata:
  name: c1static-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/static"
