apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf
  labels:
    type: local
spec:
  storageClassName: ngc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/conf"
